### ISSUE TITLE
Change trigger text on state change?

### ISSUE THREAD

**Issue by cashtotalszero** [glennflanagan/react-collapsible#1]
I'd suggest adding the ability to change the trigger text on click. For example, so the text on the trigger can say "Open collapsible" when the div is collapsed and "Close collapsible" when it is open.

**Comment by glennflanagan** [comment]
I have added the prop `triggerTextWhenOpen` which you can pass to set the text when the trigger is open. If this is not set then the trigger text will remain the same for the open and closed state.
