### ISSUE TITLE
Element disappearing  after transition on IOS 11

### ISSUE THREAD

**Issue by michael-ecb** [glennflanagan/react-collapsible#102]
Hi ,
IOS 11 safari and chrome
When content is large , some dom elements disappear or content blinking ...
I fixed it by adding a wrapper with this css : `transform: 'translate(0, 0)'`

thanks

**Comment by karltaylor** [comment]
Hey @michael-ecb, thanks for your opening your issue. If this problem is still occuring and your suggest code fixes. Please can you provide a running code sample.

Thanks
