### ISSUE TITLE
Interface 'CollapsibleProps' incorrectly extends interface 'HTMLProps<Collapsible>'.

### ISSUE THREAD

**Issue by byrnedo** [glennflanagan/react-collapsible#103]
Possible that the index.d.ts needs to be updated?
```
/Users/donal/project/node_modules/react-collapsible/index.d.ts
(4,11): Interface 'CollapsibleProps' incorrectly extends interface 'HTMLProps<Collapsible>'.
  Types of property 'tabIndex' are incompatible.
    Type 'number | null | undefined' is not assignable to type 'number | undefined'.
      Type 'null' is not assignable to type 'number | undefined'.
```
**To Reproduce**

Add react-collapsible to project

Then build
`yarn build`

**React Version**
16.4.1

**Comment by byrnedo** [comment]
Any idea @karltaylor  when the next release will get cut?

**Comment by karltaylor** [comment]
I'm doing a patch right now 😊

**Comment by byrnedo** [comment]
Nice, thanks! :)

**Comment by byrnedo** [comment]
One more question @karltaylor: how long does it take to come up on npm or yarn registries?

**Comment by karltaylor** [comment]
@byrnedo npm is now showing [2.3.1](https://www.npmjs.com/package/react-collapsible) 🎉
