### ISSUE TITLE
Nested div issue with style position

### ISSUE THREAD

**Issue by j-te** [glennflanagan/react-collapsible#105]
**Describe the bug**
A nested div (approx 8 levels) with the style property `position: absolute;` results in the content being rendered outside the collapsible. While it may not be good practice to use this property, components may require it. Therefore, do we need any mitigation or tests?

I am using the Google maps API.

**To Reproduce**
Create nested divs as a component child with the style property `position: absolute;`.

**Expected behavior**
Hide child divs.

**[jsfiddle](https://jsfiddle.net/982f3LL7/15/)**

**Comment by j-te** [comment]
Updated my post

**Comment by karltaylor** [comment]
The parent class `.Collapsible__contentInner` needs `position: relative`. See this fork
https://jsfiddle.net/3xy6awrb/

**Comment by j-te** [comment]
@karltaylor thanks for the solution. Alternatively, one could insert a new style instead of overriding `.Collapsible__contentInner` - if multiple Collapsibles don't render as required.
