### ISSUE TITLE
Incorrect type definition for triggerDisabled

### ISSUE THREAD

**Issue by TkDodo** [glennflanagan/react-collapsible#106]
**Describe the bug**

In the current type definitions, `triggerDisabled` is defined as:

`triggerDisabled?: false`

I believe this to be incorrect, as this means that you cannot set it to a `boolean`, or even to a hardcoded `true`.

I also commented on the PR here:
https://github.com/glennflanagan/react-collapsible/pull/56#pullrequestreview-148944351

**Expected behavior**
`triggerDisabled?: boolean`
or
`triggerDisabled?: true`

**Additional context**
React 16.4, Typescript 2.9

**Comment by GxDesign** [comment]
+1 for this. Currently throwing errors in my typescript app

**Comment by karltaylor** [comment]
I'll get this fixed and pushed out today.

**Comment by karltaylor** [comment]
Fixed in 2.3.2
 
https://github.com/glennflanagan/react-collapsible/commit/b6e4aedbcf751a79a65773d76e91e55281f3a452
