### ISSUE TITLE
Is there a way to trigger collapsible from  inside collapsible content ? 

### ISSUE THREAD

**Issue by karkiritish** [glennflanagan/react-collapsible#107]
I am looking for a way to trigger collapsible from collapsible content. For instance, When collapsible content is too long , scrolling up to the trigger and closing can be hectic. Is there a way to trigger collapse  in onClick event of some element inside collapsible content? Thank You.

**Comment by karltaylor** [comment]
You could create a button inside the collapsible which would `setState({ collapsibleIsOpen: false` and then use the [open prop](https://github.com/glennflanagan/react-collapsible#open--bool--default-false) to toggle the collapsible open/close.
