### ISSUE TITLE
Does not work on Safari. neither mobile or desktop

### ISSUE THREAD

**Issue by DougWoodCDS** [glennflanagan/react-collapsible#108]
**Describe the bug**
The expand/collapse does not work on Safari

**To Reproduce**
use this component on safari

**Expected behavior**
expand/collapse to work

**Comment by glennflanagan** [comment]
Hey @DougWoodCDS. Are you able to get an example in a JSFiddle so we can investigate?

**Comment by karltaylor** [comment]
Please add some more information around your Issue so we can debug better. It is currently working in Safari Version 11.1 (13605.1.33.1.2)

![out](https://user-images.githubusercontent.com/6763109/46140725-c8ad4580-c249-11e8-9842-0c87466b25d8.gif)

**Comment by btrr** [comment]
I'm using Safari 12.1, and it's not working for me. Was there a fix for this?

**Comment by glennflanagan** [comment]
@btrr it works fine in Safari 12.1 for me https://codesandbox.io/s/kowr27v19v

![out](https://user-images.githubusercontent.com/5485364/56040917-6e7c5980-5d2f-11e9-80e2-295bf3f4b4f3.gif)
