### ISSUE TITLE
Double click breaks Collapsible element

### ISSUE THREAD

**Issue by stasgavrylov** [glennflanagan/react-collapsible#118]
**Describe the bug**
Hi, and first of all, thanks for such a great component.

I've stumbled across a bug that sometimes double click on component with `triggerWhenOpen=null` leaves inner state of `Collapsible` in transition, and prevents further interaction. 
Also I suppose that it may be related to content styling `contentInnerClassName={!isCollapsibleOpen ? 'hidden' : null}`. But I was able to reproduce the bug  even without this condition, although it's much harder to reproduce constantly.

**To Reproduce**

[Reproducible example](https://jsfiddle.net/g4etwq0m/1/)

Bug is not constantly reproducible, it may take a couple of tries.
1. Click twice or thrice on trigger in closed state (so that first click is on trigger, and next ones are on content).
2. Observe empty trigger.

**Expected behavior**
Collapsible handles fast clicks correctly and always stays interactive.

**Screenshots**
![collapsible](https://user-images.githubusercontent.com/9000614/53503517-e01e8200-3ab8-11e9-99cd-6219e1cbff7c.gif)

**Comment by karltaylor** [comment]
Thanks for reporting! and +1 for adding not only a screen shot but a gif 😂🎉 Will take a deeper look at this, can't initially see what's causing so will have to do some tests

**Comment by glennflanagan** [comment]
I imagine this is because we're not blocking this.setState during transitions. We could disable click while transition is happening, this would fix this, but it means you have to wait for the animation to finish before you can collapse again.

**Comment by JayAshday** [comment]
I'm having a similar bug in my implementation of this library. In my case, I have created a separate toggle for showing and hiding the element (due to the theming and keyboard accessibility needs of the site, simply using the `trigger` from this library is not viable). If a user tabs to the button and then hits the enter and/or spacebar keys rapidly, to trigger browser click events, at some point the library stops working... the setState for open continues to fire and set a new state as expected, but the Collapsible doesn't actually show/hide its content.

```
class CollapsibleContent extends Component {
  state = {
    open: false,
  };

  toggleOpen = () => this.setState(state => {
    return {open: !state.open};
  });

  render() {
    const { title, children } = this.props;
    const { open } = this.state;

    return (
      <section className={open ? classes.open : ''}>
        <h1 className={classes.title}>
          <button onClick={this.toggleOpen}>
            {title}
          </button>
        </h1>
        <Collapsible transitionTime={200} open={open} trigger={null}>
            {children}
        </Collapsible>
      </section>
    );
  }
}
```

**Comment by YoavHortman** [comment]
Any updates on a solution? currently can't use this library in production cause of this.
