### ISSUE TITLE
Possibility to hide trigger if there are no items in sub menu.

### ISSUE THREAD

**Issue by RyanGosden** [glennflanagan/react-collapsible#119]
It would be great if the trigger can automatically hide if there are no items in sub-menu to improve user experience.

**Comment by glennflanagan** [comment]
@RyanGosden could you elaborate on what you mean? You have control over the `open` prop so if you're not passing anything into the collapsible you can set this to false.

**Comment by RyanGosden** [comment]
@glennflanagan - Thanks for the info!
I resolved the issue by adding a ternary to the trigger to check if there were any menu items for that specific Collapsible. 

```
<Collapsible
    contentOuterClassName="subNavMenu_ContainerOuter"
    className="subNavMenu_Container"
    openedClassName="subNavMenu_Container"
    trigger={
         menuItems.length > 0
             ? <FontAwesomeIcon
                      icon="angle-down"
                      className="subNavMenu_Arrow"
                  />
              : " "
      }
     triggerSibling={label}
>
<ul className="su_SubMenuList">{menuItems}</ul>
</Collapsible>```
