### ISSUE TITLE
Height issues in IE11

### ISSUE THREAD

**Issue by jlongbottom** [glennflanagan/react-collapsible#12]
The `Collapsible__contentOuter` class has `height:auto`, but in IE11 its getting a fixed height. This is causing problems for me as the content inside the collapsible component is dynamic and it has `overflow: hidden`.

Can be fixed easily with some custom CSS, but the height should behave consistently across all browsers.

**Comment by glennflanagan** [comment]
Hey @jlongbottom. I've tested out the latest code in IE11 and IE10 and it looks to be working fine. I've taken screen recordings so you can see.

- IE11 - https://youtu.be/-OXrJJy3UnU
- IE10 - https://youtu.be/PhZzy_E2fI8

Are you getting any error messages in the console? Are you able to show me an example of it not working?

**Comment by richardklotz** [comment]
I was able to reproduce this issue in IE11, but only on windows 7. IE11 in windows 10 worked fine.  What I found is that addEventListener was not attaching the event and so it never fired to turn the inline style back to auto. I fixed it by doing as the comment suggest in  componentDidMount (moving to onTransitionEnd prop).
