### ISSUE TITLE
Event Listeners functionality

### ISSUE THREAD

**Issue by utkarsh447** [glennflanagan/react-collapsible#121]
Hi, In the title bar formed after writing this  snippet, `<Collapsible trigger="Start here">`,
Is it possible to add custom `button` which can act as event listeners on that title bar?

Sorry, It's kind of `information issue`.

**Comment by utkarsh447** [comment]
No Comments?

**Comment by glennflanagan** [comment]
@utkarsh447 you can pass your own component to the trigger prop if that's what you mean? https://github.com/glennflanagan/react-collapsible#trigger--string-or-react-element--required

If not, could you describe your issue in a bit more detail?

**Comment by karltaylor** [comment]
See #120
