### ISSUE TITLE
Feature Request: Pass prop "id" to root element

### ISSUE THREAD

**Issue by j-te** [glennflanagan/react-collapsible#123]
Please can we pass element attribute `id` as a simple prop:
```html
<Collapsible id='my-elemental-identity' trigger='Title'>
  My content goes here
</Collapsible>
```

This will save us having to wrap the entire component or its contents. 

As the root element of Collapsible is always a `<div>`, it may be worth considering support of passing other attributes: `id title lang style align`.

---
***Alternatively***

What may be preferable is to have an `onRender` override. This would simply call-back the props where you could do something like:

```html
<Collapsible
  trigger="Title"
  onRender={(_event, props) => (
    <div id="my-elemental-identity">{props.children}</div>
  )}
>
  My content goes here
</Collapsible>;
```
This allows people to have complete control over the root element.

**Comment by karltaylor** [comment]
This would be a great addition @j-te. What do you think is a more preferred way of doing this?

We could add props such as `contentContainerId`, `contentContainerStyle`?

Do you have time to take a stab an open a pull request?

**Comment by j-te** [comment]
I have opted for a spreader on `<ContentContainerElement>` for new prop `containerElementProps`. It resolves the feature request above.

Although `onRender` would add more value, I didn't want to change too much or cause confusion. It can be re-visited if and when there's a specific use-case.
