### ISSUE TITLE
Expandable and selectable list at once.

### ISSUE THREAD

**Issue by mindaugasnakrosis** [glennflanagan/react-collapsible#125]
How would it be possible to achieve this:

![image](https://user-images.githubusercontent.com/14983636/63222106-bc0c4580-c1ab-11e9-9e0b-ff1332183bbe.png)

You expand the element with `plus symbol` and select the row when clicking on the `span` of text

My tried approach:
```
import { MdKeyboardArrowDown } from 'react-icons/md';

const drawChildren = children =>
  children.map(child => {
    if (child.children) {
      return (
        <div>
          <Collapsible trigger={<MdKeyboardArrowDown />}>
            {drawChildren(child.children)}
          </Collapsible>
          <span>{child.title}</span>
        </div>
      );
    }
    return <span>{child.title}</span>;
  });

const renderLocations = locations =>
  locations.map(location => (
    <div>
      <Collapsible trigger={<MdKeyboardArrowDown />}>{drawChildren(location.children)}</Collapsible>
      <span>{location.title}</span>
    </div>
  ));

const WarehouseMap = ({ locations }) => 
      renderLocations(locations)
};
```

```
const locations = [
  {
    title: 'Main warehouse',
    children: [
      {
        title: 'A zone of warehouse',
        children: [{ title: '1 row' }, { title: '2 row' }, { title: '3 row' }],
      },
    ],
  }];

```
Result achieved:
![image](https://user-images.githubusercontent.com/14983636/63222202-21ad0180-c1ad-11e9-9def-4a0e46861725.png)

`
Main warehouse` should be the most top element.
`Main warehouse` has **A zone of warehouse** beneath it.
`A zone of warehouse`  has 1 row, 2 row, 3 row beneath it.

How to make spans do not move the bottom once collapsible is expanded?

**Comment by mindaugasnakrosis** [comment]
@glennflanagan @karltaylor maybe you have any ideas?
I hope not bothering you too much.

**Comment by karltaylor** [comment]
@mindaugasnakrosis Would you mind trying to make an [SSCCE](http://sscce.org/) on CodeSandbox and I could take a look?

**Comment by mindaugasnakrosis** [comment]
@karltaylor 
https://codesandbox.io/s/react-collapsible-wb49k

**Comment by karltaylor** [comment]
@mindaugasnakrosis This is a super interesting challenge 😊 but I don't have the capacity to look at it in depth at the moment, if you are time constrained it may be worth looking at https://github.com/pczern/react-collapsible-tree, see the [demo](https://pczern.github.io/react-collapsible-tree/demo/).

**Comment by mindaugasnakrosis** [comment]
@karltaylor I am not in a hurry :)
The problem with `react-collapsible-tree` is that it select the row on expand.
I want to have two different actions: expand and select.

**Comment by kevinpallado** [comment]
Any update on this? Hoping for some tricks that might work related on this issue

**Comment by glennflanagan** [comment]
This is not really an issue with this library. This is a simple collapsible component, not a tree component. 

You could achieve a tree-like layout by nesting collapsibles inside one another and then use recursion to build your tree out - but this is beyond the scope of this project. Maybe have a look on NPM for React tree components, or head over to StackOverflow to see if anyone there can help out.
