### ISSUE TITLE
Collapsing/expanding all collapsible elements

### ISSUE THREAD

**Issue by N0nny** [glennflanagan/react-collapsible#13]
Is it possible to use the `.Collapsible__trigger` and `is-closed`/`is-open` to make a collapse all function?
-- I tried using it with `GetElementsByClassName` and modifying it from is-closed to is open, but this didn't seem to do anything.

**Comment by glennflanagan** [comment]
This probably won't work as the animation is hard-baked into the code. 

You should use the `open` prop and change that value if you want to open and close it programmatically. 

https://www.npmjs.com/package/react-collapsible#open--bool--default-false
