### ISSUE TITLE
Only have one collapsible component open at a time

### ISSUE THREAD

**Issue by pmdownie** [glennflanagan/react-collapsible#14]
Is it possible to have only one collapsible element open at one time?

So for example if one component is open, and a user clicks on another trigger it animates that component open and closes all others?

**Comment by glennflanagan** [comment]
The component is stand-alone but you can achieve it quite simply by managing a wrapper component state to control which one is open. 
I did [create](https://github.com/glennflanagan/react-responsive-accordion) this but I've not maintained it for a while. But if you have a look at the src you can see how I did it.

**Comment by texas697** [comment]
trying to figure out how to do this. can you show a example?

**Comment by mparker11** [comment]
For anyone else trying to figure this out, try adding a state like `currentOpen: false`. Then for the Collapsible code, add the following:
```
<Collapsible
    open={ this.state.currentOpen === 'something-unique' }
    handleTriggerClick={ () => this.setState({ currentOpen: 'something-unique' }) }
>
    Collapsible stuff in here
</Collapsible>
```
And to allow clicking the same collapsible to close it, create a function that detects if the state is set to the open one, then set state to false again.
