### ISSUE TITLE
index.d.ts: add React import

### ISSUE THREAD

**Issue by uwolfer** [glennflanagan/react-collapsible#143]
I get the following errors:
```
node_modules/react-collapsible/index.d.ts(1,35): error TS2686: 'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.
node_modules/react-collapsible/index.d.ts(42,3): error TS2666: Exports and export assignments are not permitted in module augmentations.
```

Is there a reason why you do not import React before using it? I'd suggest adding this line at the top of the file to fix the first of these two errors:
`import * as React from 'react';`

For the 2nd issue, you probably could take a look at this solution:
https://github.com/brunolemos/react-native-linear-gradient/pull/1/files

**Comment by glennflanagan** [comment]
Is this happening in a typescript project for you? I’m not massively familiar with Typescript definitions so if you have a solution feel free to open a PR

**Comment by narthollis** [comment]
I am also experiencing these issues with the current type definitions.

I have had a look at the associated PR and this looks like it will resolve the issues I am experiencing.

**Comment by mikebean81** [comment]
My typescript project is also experiencing the same problem (first error) with the recent package update (2.6.2). I was able to temporarily resolve this by forcing the build to a prior version.

**Comment by uwolfer** [comment]
> Is this happening in a typescript project for you? I’m not massively familiar with Typescript definitions so if you have a solution feel free to open a PR

@glennflanagan: Would be great if you could look into my PR - I'm also happy to work on it if there is any feedback.

**Comment by karltaylor** [comment]
https://github.com/glennflanagan/react-collapsible/pull/144
