### ISSUE TITLE
clicking on CollapsibleContent to open and close it automatically fires forms submit event

### ISSUE THREAD

**Issue by Nileshdcool** [glennflanagan/react-collapsible#145]
I have a form inside which I have  <CollapsibleComponent>
the problem is that whenever I click CollapsibleContent  to open, it somehow invokes form submit an event

**Comment by glennflanagan** [comment]
@Nileshdcool the likely thing here is the trigger to open the collapsible is a <button> element which when clicked is submitting the form by default. Best option is to `event.preventDefault()` on that button. 

If you’ve got a code example then post it here and we can try and help a bit more.
