### ISSUE TITLE
Be able to set custom properties on trigger element

### ISSUE THREAD

**Issue by MattBodey** [glennflanagan/react-collapsible#146]
**Describe the bug**

When running accessibility audits using [axe pro](https://axe.deque.com) and enabling tab index, it was noted that there is no role on the Trigger element. 

This lead to us realising that there is no way of passing props to the trigger element. In our case, this would be for aria roles and labels. 

**To Reproduce**

Try and pass properties to the trigger element

**Expected behaviour**
There should be some way of setting additional properties on the trigger element. As there is already a containerElementProps prop, it would be nice to have a triggerElementProps prop on the Collapsible. This would allow the passing of an object that would set props on the TriggerElement

I'm happy to raise a PR for this if you would like

**Comment by karltaylor** [comment]
Hey @MattBodey,

Sounds good to me, something like {...triggerElementProps} on the `<TriggerElement />`, would that suffice?

Feel free to raise a PR and I'll take a look for you

**Comment by MattBodey** [comment]
That's exactly what I was thinking!
I've raised a PR.
