### ISSUE TITLE
Disable open or close transition when click a button inside Collapsible

### ISSUE THREAD

**Issue by shunmian** [glennflanagan/react-collapsible#159]
Is there a way to disable certain children's triggering of the Collapsible open or close?

I have the following code, which aims to open or close Collapsible by clicking `renderVisibleItem` except the button inside it.

```
<Collapsible key={item.Id} trigger={renderVisibleItem()} >
   <p>This is the collapsible content</p>
</Collapsible>
```
and
```
const renderVisibleItem = () => {
  return (
   <div>
     <p>Click this should open or close the Collapsible<p>
     <button onClick={clickButton}>
       Click this should only trigger button's onClick, not open or close the Collapsible. How Can I achieve this?
     </button>
   </div>
  )
}
```
Is this achievable?

**Comment by glennflanagan** [comment]
In your 'clickButton' function use event.stopPropagation and that should do it. 

https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation
