### ISSUE TITLE
Automatically close the list that was open when a list was already open

### ISSUE THREAD

**Issue by kevinpallado** [glennflanagan/react-collapsible#161]
**Describe the bug**
There is no function to determine the list that was open, is there a function or other method on how to make that work?

**To Reproduce**
npm install react-compatible

**Comment by glennflanagan** [comment]
Could you give a bit more detail as to what you are expecting?

**Comment by kevinpallado** [comment]
When there is already one collapsible open, and if you click the other collapsible the first one must closes first before it opens the other one, see this ![output](https://user-images.githubusercontent.com/31546211/85575063-d9326000-b669-11ea-9a7a-b8bd45a512d4.png) the image shows the current setup of the package

**Comment by glennflanagan** [comment]
You're looking for an **accordion** component - this is a collapsible component. 

You can implement an accordion using this component by utilising [the `onOpen` and `onClose` methods ](https://github.com/glennflanagan/react-collapsible#onopen--function). I have a different repo  for as an example of how to do it (but bear in mind I have not maintained the other repo)
https://github.com/glennflanagan/react-responsive-accordion

Here's a link to the source for how I did it.
https://github.com/glennflanagan/react-responsive-accordion/blob/master/src/Accordion.js
