### ISSUE TITLE
Trigger collapse and uncollapse programmatically

### ISSUE THREAD

**Issue by anir1234** [glennflanagan/react-collapsible#164]
Is it possible to initiate trigger programmatically using react-collapsible , without actually clicking the element.
Basically i need to call the trigger using a button which will collapse the element if it is uncollapsed and vice -versa.

**Comment by glennflanagan** [comment]
Yep this is possible by managing the `open` prop. 

https://github.com/glennflanagan/react-collapsible#open--bool--default-false
