### ISSUE TITLE
Animating the icon in the span trigger

### ISSUE THREAD

**Issue by jaygrestoplus** [glennflanagan/react-collapsible#165]
Hi there, I've been working on an interface that requires the chevron/arrow to be animated on the trigger span. I managed to display the icon on the right-hand side, but I'm a bit stuck now on how to animate it as the collapsible is clicked. Sample code I did here: https://codesandbox.io/s/sleepy-framework-pvvvx

Appreciate any input on this one.

**Comment by glennflanagan** [comment]
You can make use of the .is-open CSS selector and do this 

```

.la.la-arrow-down {
  transition: transform 200ms ease;
}

.is-open .la.la-arrow-down {
  transform: rotate(0.5turn)
}
```

I've saved what I did here. https://codesandbox.io/s/pensive-ishizaka-6c5lb

**Comment by jaygrestoplus** [comment]
This is great, thanks for the tip. :smile:
