### ISSUE TITLE
npm install react-collapsible still has openCollasible() typo

### ISSUE THREAD

**Issue by Redmega** [glennflanagan/react-collapsible#17]
Mayhaps the npm package needs to be updated?

**Comment by glennflanagan** [comment]
@Redmega the fix for that was corrected in #11, merged and released in v1.2.1 on Jan 24th. Please update your package.json to v1.2.1.

Thanks

**Comment by Redmega** [comment]
`"react-collapsible": "^1.2.1",` is what I have in my `package.json`,

Running `npm install react-collapsible@1.2.1` has the type on line 117 `this.openCollasible();`

I noticed that 1.3.0 is available as the latest, so I'll update to that one as it has the corrected method name.
