### ISSUE TITLE
v2.8.2 breaks server-side rendering

### ISSUE THREAD

**Issue by dlong500** [glennflanagan/react-collapsible#179]
**Describe the bug**
v2.8.2 references the window object without checking that it's available which crashes during server-side rendering.  This did not occur in previous versions.

**To Reproduce**
Use the library in a project that renders a component server-side

**Expected behavior**
The window object should not be referenced unless it is available, so any initialization in a render should check if a browser environment is available first before calling any window object attributes or methods.

**Comment by parichay-batra** [comment]
Yes, facing the same issue. 
Resolved it by moving to version v2.8.1

**Comment by karltaylor** [comment]
Thanks for flagging, fixed in `2.8.3`. I've deprecated `2.8.2` on npm.
