### ISSUE TITLE
support for aria labels

### ISSUE THREAD

**Issue by vishalkhialani** [glennflanagan/react-collapsible#196]
If the component is expanded we would like to add `aria-expanded=true` for accessibility.

How can we get this done ?

Thank you,
vishal

**Comment by karltaylor** [comment]
I'd love to start making react-collapsible more accessible!

If follow the w3 spec for Accordions, this could be a great addition.

https://www.w3.org/TR/wai-aria-practices/#accordion

Feel free to open a PR and we can take a look

**Comment by vishalkhialani** [comment]
Hi @karltaylor ,
Sorry, I don't currently have the personal bandwidth to dedicate time to code and make  pull requests.
If I get free I will get back to you.
Thank you,
Vishal

**Comment by louisnk** [comment]
Can somebody please merge the referenced PR #197 and the dependabot bumps and deploy a new version of the package? 🙏 Would be most grateful.

**Comment by glennflanagan** [comment]
All sorted. 2.8.4 just been published
