### ISSUE TITLE
Set the focus on the top of the unfolded collapsible

### ISSUE THREAD

**Issue by cedricmessiant** [glennflanagan/react-collapsible#2]
Is there a way to set the focus on top of the component when it is unfolded ?

**Comment by glennflanagan** [comment]
@cedricmessiant I'm not sure I follow what you're after.

What do you want focused when open?

**Comment by cedricmessiant** [comment]
Oh, in fact, it seems to be a bug in react-responsive-accordion instead... I'm really sorry !
