### ISSUE TITLE
Closing other tabs when opening a new one?

### ISSUE THREAD

**Issue by kawern** [glennflanagan/react-collapsible#203]
Hi, maybe its just me not reading the docs correctly, but is there a way to close other "tabs" when clicking (opening) a new one?

**Comment by glennflanagan** [comment]
You can use the [`open`](https://github.com/glennflanagan/react-collapsible#open--bool--default-false) prop to manage the open state of the collapsible, so you'd need to close all other collapsibles from a parent component.

I did create this (but it's not maintained) but it'll give you an idea on how to do it https://github.com/glennflanagan/react-responsive-accordion
