### ISSUE TITLE
Uncaught TypeError: Super expression must either be null or a function

### ISSUE THREAD

**Issue by jakub-zawislak** [glennflanagan/react-collapsible#212]
I have the 

> Uncaught TypeError: Super expression must either be null or a function

error using this library. It occurs with the simplest code, like 
```tsx
import Collapsible from 'react-collapsible'

// ...

    <Collapsible trigger="Start here">
      <p>
        lorem ipsum
      </p>
    </Collapsible>
```

It throws only in a production webpack build.

I'm using a lot of libraries in my project and this is the first time that this error is caused by some library.

* `react` `16.11.0`
* `react-collapsible` `2.8.4`
* `@symfony/webpack-encore` `0.31.0`
* `webpack` `4.44.2`

**Comment by madeleineostoja** [comment]
Apologies for reviving an ancient issue, but just in case anyone else comes across this — I was getting this with React server components, fixed it by forcing `"use client"` on the component/page that used it. 

I haven't had this issue with any other 3rd party libs so must be something a little funky in how `react-collapsible` is architected?
