### ISSUE TITLE
Unable to pass key prop

### ISSUE THREAD

**Issue by rfrancesca12** [glennflanagan/react-collapsible#232]
I'm using `containerElementProps` to pass in additional props to the parent element but the key prop isn't showing up. Because of this, i'm getting an issue `Each child in a list should have a unique "key" prop.`
```
containerElementProps={{ key: event.id, id: collapsible-${event.id} }}
```
Is there a way to pass in the key prop? Thank you!

<img width="424" alt="Screen Shot 2022-08-12 at 12 47 04 PM" src="https://user-images.githubusercontent.com/52517362/184424159-c78ff41b-50fb-4c6a-af1c-c370bebc9943.png">

**Comment by glennflanagan** [comment]
You just need to apply the key prop to the component itself as that’s how keys work in React. 

https://reactjs.org/docs/lists-and-keys.html#keys

It’s not something that ends up in the rendered DOM - `containerElementProps` is designed to pass props which will get applied to the DOM, things like “id” or “aria-describedby” etc.
