### ISSUE TITLE
NPM install does not install the latest code.

### ISSUE THREAD

**Issue by matzero** [glennflanagan/react-collapsible#25]
If I do a `npm install react-collapsible ` I don't seem to get the latest version of Collapsible.js that I see in the `development` branch. For instance the _onOpen_ does not exists in master The work around was to copy paste the latest Collapsible.js (development) in my project install the create-react-class dependency. Using the latest works with onOpen prop.

**Comment by glennflanagan** [comment]
The onOpen functionality has not been released to NPM yet. I'm planning on doing this with a v2 release in the near future. Watch this space

**Comment by ramusus** [comment]
@glennflanagan It would be nice to have in npm new functionality from development branch. For example version 1.4.1 could be created prior 2.0. Right now there is no possibility to get new features. It's even impossible to install from github directly - there is no `dist` directory in repo.

**Comment by glennflanagan** [comment]
@matzero @ramusus sorry it's taken so long but this is now available in v1.5.0.
