### ISSUE TITLE
Is it possible to programmatically close a collapsible? 

### ISSUE THREAD

**Issue by kellyjoyner** [glennflanagan/react-collapsible#26]
I created a component that has several collapsibles. Inside each collapsible I have individual forms. Upon the submit of each form I would like to close the collapsible component and render the submitted form value in the label. Is it possible to programmatically close the collapsible based on an action (submit)?

Note: I did notice you have `handleTriggerClick`; however, this would only allow me to override what you are already doing for the open/close, which is functionality I do not want to lose.

**Comment by makkBit** [comment]
Not the best solution. But this is what I did to achieve this.
```
<Collapsible trigger="heading1">
   <p> body1 </p>
</Collapsible>

// wrap the component in a div, and attach an event to it
<div onClick={ this.handleOnClick.bind(this) } >
  <Collapsible trigger="heading2">
        <p> body2 </p>
  </Collapsible>
</div>

// this would close the first collapsible component (heading1)
handleOnClick(){
    $('span').click();
}
```

**Comment by glennflanagan** [comment]
@kellyjoyner you can manage whether the Collapsible is open via a containing component state using the **open** prop.

https://github.com/glennflanagan/react-collapsible#open--bool--default-false
