### ISSUE TITLE
How can I customize the style of the 'trigger' ? 

### ISSUE THREAD

**Issue by aziz-boudi4** [glennflanagan/react-collapsible#28]
How can I style the trigger element, I would like to add a border and some styling but I couldn't get the info from the doc ?

**Comment by thifranc** [comment]
triggerClassName to pass as props :  
See this example :  
```
<Collapsible
     triggerClassName={yourStyle}
>
{yourInputCollapsible}
</Collapsible>
```

**Comment by aziz-boudi4** [comment]
I'm having this error `Invalid` prop `triggerClassName` of type `object` supplied to `Collapsible`, expected `string`.`

Can I pass my style like this :
`<Collapsible triggerClassName={{ color: 'red' }}>
     {yourInputCollapsible}
  </Collapsible>`

**Comment by glennflanagan** [comment]
@aziz-boudi4 `triggerClassName` expects a string so you can style it with CSS seperate to the Javascript. 

https://github.com/glennflanagan/react-collapsible#triggerclassname--string

Take a look at the example code too to show you how it works.
