### ISSUE TITLE
Have more than 1 data-trigger ?

### ISSUE THREAD

**Issue by kuldeepdaftary** [glennflanagan/react-collapsible#31]
Can we have more than 1 data trigger so, for example, if I pass
`data-trigger={['text 1', 'text 2']} `

it renders it as
```
<span class="Collapsible__trigger is-open">
  <span class="Collapsible__trigger--content-1"> text 1 </span>
  <span class="Collapsible__trigger--content-2"> text 2 </span>
</span>
```

**Comment by kuldeepdaftary** [comment]
Never mind I just realised that we can pass an element as data-trigger.

Thank you for this amazing component.

**Comment by zeeshanjan82** [comment]
@kuldeepdaftary how can we pass element as data-trigger any example code?
