### ISSUE TITLE
close other siblings if one collapse will open

### ISSUE THREAD

**Issue by turdiyev** [glennflanagan/react-collapsible#32]
Hi there. 

Could you do this logic: close other siblings if one collapse will open.

I'm facing this problem with many collapsible item in small popup. So, there is scrollable content, But if you open last one which is visible in modal, UI problem happens.

**Comment by glennflanagan** [comment]
This component is not an accordion component. If you want accordion functionality then you can achieve this by wrapping the Collapsible with another component and then manage the state of the `open` prop

**Comment by turdiyev** [comment]
Thank you? It works (with `open` state)
