### ISSUE TITLE
Any chance of a minor release in the near future? Would love to take advantage of the open and close trigger hooks

### ISSUE THREAD

**Issue by hixme-technology** [glennflanagan/react-collapsible#35]
Thanks for building and sharing this component.  It works great for my needs.  I've been using it on a local branch with my package.json pointing to a sha with the open/close triggers.
`"react-collapsible": "git+ssh://git@github.com:glennflanagan/react-collapsible.git#1b6065a",`

 I am eagerly awaiting your next release.  If there is any way I can help out to expedite that process, please let me know.

Thanks,
 
Joel

**Comment by glennflanagan** [comment]
@hixme-technology sorry it's taken so long (I became a dad in November so parenting > coding at the moment).

I have now released that feature into [v1.5.0](https://github.com/glennflanagan/react-collapsible/releases/tag/1.5.0) which is also released on NPM.

Thanks
