### ISSUE TITLE
How to pass css to obtain the style demonstrated in the gif?

### ISSUE THREAD

**Issue by ambarbs** [glennflanagan/react-collapsible#44]
The component is working fine but I'd like to make it more like a collapsible component. Maybe like the wait looks in the demo.
![image](https://user-images.githubusercontent.com/13555224/29664585-909a0964-8913-11e7-90ed-ae318bbb057d.png)

How do I pass in some style to change the background colour and the title text font.

**Comment by glennflanagan** [comment]
@ambarbs you don't need to pass styles in, you can use CSS using the built in [class names](https://github.com/glennflanagan/react-collapsible#css-styles) or you can override the class names to be whatever you wish using the [css class overrides](https://github.com/glennflanagan/react-collapsible#css-class-string-props)

**Comment by ambarbs** [comment]
Hi @glennflanagan ,

Would like to thank you for developing this handy component and also for the quick reply.

Currently I am using it in some places in my app. Works great!

**Comment by glennflanagan** [comment]
Thanks. It's rare to get messages like this so thank you very much!
