### ISSUE TITLE
Auto-collapse 

### ISSUE THREAD

**Issue by barimani** [glennflanagan/react-collapsible#45]
In the API I can't find a functionality (maybe a Boolean property) to force collapse siblings of Collapsibles. I would like to have only one collapsible open at a time.
P.S. thanks for the good work

**Comment by barimani** [comment]
Just found it in the closed issues

**Comment by zilahir** [comment]
@barimani and what is the solution? i also want to solve to have one elemtn open at a time, and close automaticall if an other one is treggered. this is what u meant? if so, how did u solve it? :) thanks!
