### ISSUE TITLE
UNMET PEER DEPENDENCY react-collapsible@2.0.0

### ISSUE THREAD

**Issue by ShunmugamAiyappan** [glennflanagan/react-collapsible#47]
`-- UNMET PEER DEPENDENCY react-collapsible@2.0.0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN react-responsive-accordion@1.0.0 requires a peer of react-collapsible@^1.3.0 but none was installed.
npm ERR! code 1

**Comment by glennflanagan** [comment]
Hi @ShunmugamAiyappan could you tell me what steps you took to get this error? 

Thanks

**Comment by ShunmugamAiyappan** [comment]
npm install react --save 


npm install react-collapsible --save

**Comment by glennflanagan** [comment]
@ShunmugamAiyappan I'm not able to replicate this for this component, however I have noticed that this is an issue with the [react-responsive-accordion](https://github.com/glennflanagan/react-responsive-accordion) when you try to install that. I've not updated the accordion component for a while so I would raise an issue in that repo so it is visible there.
