### ISSUE TITLE
Using two collapsible boxes side by side in a row causes them both to expand on click

### ISSUE THREAD

**Issue by tomkennedycode** [glennflanagan/react-collapsible#49]
I would like to use two boxes in a row side by side -

When you click the arrows for one, the box expands on the other. is there a way around this?

![capture](https://user-images.githubusercontent.com/26717461/30281397-2d5b958e-970a-11e7-9f46-57ab5fcb3feb.PNG)

Thank you

Tom

**Comment by glennflanagan** [comment]
Hi Tom, you can achieve this by managing the `open` prop from a parent component.
