### ISSUE TITLE
overflowWhenOpen does not work

### ISSUE THREAD

**Issue by tyrsius** [glennflanagan/react-collapsible#50]
Im using `overflowWhenOpen='visible'` on an uncontrolled Collapsible, and it doesn't seem to do anything. It looks like the [only reference](https://github.com/glennflanagan/react-collapsible/blob/develop/src/Collapsible.js#L21) to this property is when `this.props.open` is set. Is this property only supposed to work when the Collapsible is controlled?

**Comment by williamboman** [comment]
#48 fixes this

**Comment by tyrsius** [comment]
@williamboman No, I tried pulling that down and it still has `overflow: 'hidden'` set when open

**Comment by williamboman** [comment]
> @williamboman No, I tried pulling that down and it still has overflow: 'hidden' set when open

Hm, for me that PR fixes the exact same issue you're having.

I've temporarily published a copy of this npm package called `react-collapsible-react16`, try installing that one and see if that works perhaps? (reminder that it's a temporary npm package)

**Comment by tyrsius** [comment]
Yea, that works. Must have had some caching somewhere

**Comment by tyrsius** [comment]
@williamboman Do you know when that fix will be released on the main package?

**Comment by glennflanagan** [comment]
@tyrsius I'm looking into doing a release just now. Keep an eye out 👀

**Comment by glennflanagan** [comment]
The fix has been published to v2.0.1.
