### ISSUE TITLE
Please put react as a peer dependency instead

### ISSUE THREAD

**Issue by ahmadsholehin** [glennflanagan/react-collapsible#52]
Please put `react` in `peerDependencies` for best practices. Consuming apps are getting react dups (see https://facebook.github.io/react/warnings/refs-must-have-owner.html).

**Comment by glennflanagan** [comment]
v2.0.1 fixes this. Thanks

**Comment by ahmadsholehin** [comment]
Awesome! Thanks for the speedy response @glennflanagan! 👍

**Comment by ahmadsholehin** [comment]
Oh wait, sorry. React and react-dom are still in dependencies:
```
"dependencies": {
    "react": "^15.6.1",
    "react-dom": "^15.6.1"
  },
```
They're in peerDependencies as well:
```
"peerDependencies": {
    "prop-types": "^15.5.8",
    "react": "~15 || ~16",
    "react-dom": "~15 || ~16"
  },
```
