### ISSUE TITLE
HTML in Collapsible Content

### ISSUE THREAD

**Issue by jacksonp2008** [glennflanagan/react-collapsible#55]
Hi Glenn, 

Great component, thanks for sharing.  In my case I have HTML as the Collapsible content.  My trigger is a string, but the content below is HTML via a const,   It would be awesome if the HTML could be rendered, rather than just showing the code.  Any ideas on how I can make that work?

Thanks!

**Comment by glennflanagan** [comment]
Hi @jacksonp2008. The component should render any React component you give to it, so if your HTML was a React component then it should work. If you're just passing a string of HTML code then this won't work as the component just assumes it's a string and would be dangerous to allow any old HMTL to be rendered out.

Have you got an example of how you're trying to use it that you could put in a Codepen or JSBin? That way I can try and help advise you on what's best to do, or decide if we should add a new feature.

**Comment by jacksonp2008** [comment]
thanks Glenn, I'm working through it based on your feedback.
