### ISSUE TITLE
Enable user selection of trigger wrapper (span currently) element to prevent div inside span

### ISSUE THREAD

**Issue by esalaza** [glennflanagan/react-collapsible#58]
Hi, Glenn.

Thanks for this great component. The default trigger wrapper is a `span` element. This is great for when the user supplies only text as the trigger, but as the component also permits the use of arbitrary React elements, I guess it won't be uncommon for the user to supply `div`s, ending up with `div`s inside the `span` (invalid HTML).

I propose the creation of a new property named `triggerComponent` (or `triggerElement`) with 'span' as the default value (for backward compatibility) which can be used to specify other values such as ' div'.

PR: #57

Thank you.

**Comment by karltaylor** [comment]
Merged 💯
