### ISSUE TITLE
[docs] Unable to run the included example locally

### ISSUE THREAD

**Issue by akshaynaik404** [glennflanagan/react-collapsible#63]
Steps I followed:

1. cloned the react-collapsible repo
2. installed webpack and webpack-dev-server globally (although not necessary)
3. cd'd into react-collapsible/ and did `npm i`
4. run `webpack-dev-server`

Here are the errors: 

```
ERROR in ./src/Collapsible.js
Module not found: Error: Can't resolve 'prop-types' in '/home/akshay.naik/Documents/react-collapsible/src'
 @ ./src/Collapsible.js 13:17-38
 @ ./example/_src/js/index.js
 @ multi (webpack)-dev-server/client?http://localhost:9000 ./example/_src/js/index.js

ERROR in ./example/_src/js/index.js
Module not found: Error: Can't resolve 'react' in '/home/akshay.naik/Documents/react-collapsible/example/_src/js'
 @ ./example/_src/js/index.js 3:13-29
 @ multi (webpack)-dev-server/client?http://localhost:9000 ./example/_src/js/index.js

ERROR in ./src/Collapsible.js
Module not found: Error: Can't resolve 'react' in '/home/akshay.naik/Documents/react-collapsible/src'
 @ ./src/Collapsible.js 9:13-29
 @ ./example/_src/js/index.js
 @ multi (webpack)-dev-server/client?http://localhost:9000 ./example/_src/js/index.js

ERROR in ./example/_src/js/index.js
Module not found: Error: Can't resolve 'react-dom' in '/home/akshay.naik/Documents/react-collapsible/example/_src/js'
 @ ./example/_src/js/index.js 7:16-36
 @ multi (webpack)-dev-server/client?http://localhost:9000 ./example/_src/js/index.js

```

**Comment by akshaynaik404** [comment]
I looked at the output of `npm i` and it's instructing me to install prop-types, react, react-dom dependencies manually. Doing so fixes the errors and the example works.

We can include this in README.md.

You can acknowledge this and close the issue.

**Comment by blord-fullscreen** [comment]
This isn't working for me. Even after manually installing prop-types, react, and react-dom, the project won't build at all. It would be great to see the working example hosted somewhere live, with the demo linked out at the top of the readme.

**Comment by karltaylor** [comment]
@blord-fullscreen I've added the devDependencies required to run the example and have the example working fine. Are you still having issues?
