### ISSUE TITLE
collapsible is not closing

### ISSUE THREAD

**Issue by D063520** [glennflanagan/react-collapsible#66]
Hello, 

we have a very basic problem. We have imported the library and integrated your basic example. By clicking on start the menu opens but it does not close again. There is no way to let it close again. Did you experience this problem?

Thank you
Dennis

**Comment by glennflanagan** [comment]
Hey @D063520, 

Are you able to share an example of your code setup so I can investigate?

**Comment by D063520** [comment]
Thank you for the fast response. You can find the code in the following github repository:
https://github.com/WDAqua/Trill
under the branch 
collapsible
here is the code I pushed:
https://github.com/WDAqua/Trill/commit/8dc2cc867c1e0a9685d3b511147ac25b8149ae00
Thank you
Dennis

**Comment by glennflanagan** [comment]
The only thing I can see is that you're using a really old version of React. Are you able to try it with React v15 or v16 and see if you get the same issue?

**Comment by D063520** [comment]
Yes, this was exactly the problem. Thank you very much!
