### ISSUE TITLE
Collapsibles never closing

### ISSUE THREAD

**Issue by addinall** [glennflanagan/react-collapsible#67]
I think I tracked it down to 

onTransitionEnd=(this.handleTransitionEnd}

Never being fired.  It was the parent Accordion I modified for my use, not your code!
Everything else seems to work apart from this trigger, and as such the two calls to setState are never being called.

Any ideas why this might be happening?
Cheers.

**Comment by addinall** [comment]
I probably stuffed it up changing to ES6 syntax.

**Comment by glennflanagan** [comment]
@addinall can you open a JSFiddle example of the bug? I can't understand it from your description

**Comment by InfernoZeus** [comment]
I've discovered that onTransitionEnd doesn't fire when `transitionTime` is set to 0 - i.e. an instant expand/collapse. It seems that if you want to support that, it needs a special case which calls handleTransitionEnd directly.

**Comment by karltaylor** [comment]
@InfernoZeus if that's the case please refer to [this issue](https://github.com/glennflanagan/react-collapsible/issues/61#issuecomment-340932339) about transition time being zero.

**Comment by InfernoZeus** [comment]
Whoops, I didn't see that issue as it was already closed. Will comment there.
