### ISSUE TITLE
How to add chevron image on collapisible header.

### ISSUE THREAD

**Issue by arpit7j** [glennflanagan/react-collapsible#73]
How can we add up/down chevron image on collapsible header.

**Comment by eronisko** [comment]
One thing you can do is to pass your header (including the chevron image) as the `trigger` prop. You can then control the state of the `Collapsible` and the header by an internal state value, e.g.:

```javascript
<Collapsible 
  trigger={this.renderHeader()}
  open={this.state.isOpen}
  handleTriggerClick={() => this.setState({ isOpen: !this.state.isOpen })}
>
  // ...
</Collapsible>
```

Also check out https://github.com/glennflanagan/react-collapsible/tree/develop/example to see how this can be achieved with CSS.

**Comment by unit57** [comment]
It looks like you need the CSS provided in the demo to get the chevron image. It's sort of hinted at in the docs -  "with a little css" written after the example code. Its not in the node module so just copy and paste it from here [https://github.com/glennflanagan/react-collapsible/blob/develop/example/_src/sass/components/_Collapsible.scss](url)

**Comment by WarHatch** [comment]
@unit57 that link seems to no longer work

**Comment by eronisko** [comment]
@WarHatch Try this one: https://github.com/glennflanagan/react-collapsible/blob/develop/example/_src/sass/components/_Collapsible.scss

**Comment by slimandslam** [comment]
This link above no longer works.

**Comment by karltaylor** [comment]
> This link above no longer works.

Did you even try and search for the file? There's a search box top left - https://github.com/glennflanagan/react-collapsible/search?q=_Collapsible.scss&type=commits
