### ISSUE TITLE
radio button label in Trigger area doesn't affect radio input

### ISSUE THREAD

**Issue by amireitan** [glennflanagan/react-collapsible#74]
Hi,
Awesome component! appreciated!
I'm trying to add action element in trigger area like dropdown/radio buttons
each radio button have a label with "for" attribute - clicking on the label doesn't triggering the radio input change event.

**Sample html inside trigger area:**
```
<div class="radio-group">
    <div>
        <input type="radio" id="radio-input-xx" name="xxx" value="Standard_Application">
        <label class="radio-button-label standard-configuration" for="radio-input-xx">Standard</label>
    </div>
    <div>
        <input type="radio" id="radio-input-xx" name="xxx" value="Custom_Deployment">
        <label class="radio-button-label custom-configuration" for="radio-input-xx">Custom</label>
    </div>
</div>
```

**Comment by glennflanagan** [comment]
@amireitan I'm not sure how this is relevant to react-collapsible. From your HTML example above you need to correct your `label`'s `for` attribute to be the id of the input. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#attr-for
