### ISSUE TITLE
Make it possible to override state classes

### ISSUE THREAD

**Issue by Windvis** [glennflanagan/react-collapsible#76]
The state classes (.is-closed, is-open, .is-disabled) are not overridable.

I'm working on a project which uses CSS Modules and I'm trying to style a child element of the trigger element depending on the open / closed state. 

I don't think that this is possible with the current implementation without also storing the state in a wrapper component (and using that to set a class on the child element).

**Comment by NindroidX** [comment]
It's possible to work around this by using the overridable open classes (openedClassName 
 and triggerOpenedClassName) but I still think it would be a good idea to make all classes overridable.

**Comment by glennflanagan** [comment]
@NindroidX you can style child elements based on the state of the component by using `.is-closed` etc. 

Something like this would work
```
.Collapsible.is-open + .Collapsible____contentOuter .childElementSelector {
 /* Open Styles go here*/
}

.Collapsible.is-closed + .Collapsible____contentOuter .childElementSelector {
 /* Closed Styles go here*/
}
```

I agree having overrides would be a good feature so feel free to open a PR

**Comment by karltaylor** [comment]
I also faced this problem which would cause the wrong class names to be generated using CSS modules
