### ISSUE TITLE
Maintainers Wanted

### ISSUE THREAD

**Issue by glennflanagan** [glennflanagan/react-collapsible#78]
I'm finding increasingly difficult to keep up with maintaining react-collapsible so I'm looking for maintainers/collaborators so if you're up for some Open Source goodness then let me know in this issue. 👍

**Comment by adeolabadmus** [comment]
Hi @glennflanagan. I use this library on a project at work. It has been very useful. I'll love to help maintain it.

**Comment by glennflanagan** [comment]
@adeolabadmus I've sent you a collaborator invite 👍

**Comment by rsarai** [comment]
Hey @glennflanagan, I also use this library at work and I want to collaborate too!

**Comment by karltaylor** [comment]
We @workshoptech use it :) happy to help collab

**Comment by glennflanagan** [comment]
Hey @karltaylor, bear with me as I'm still new to this Collaborator stuff. Shall I make yourself a collaborator?

**Comment by karltaylor** [comment]
@glennflanagan Yep I'd love to

**Comment by charlesrochati** [comment]
@glennflanagan, i too would love to help in any way i can.

**Comment by brentmclark** [comment]
@glennflanagan I use this on a few projects at work and would be glad to help!

**Comment by bvmcode** [comment]
I can help if you still need collaborators

**Comment by JosephScript** [comment]
I would love to help too. I use this on multiple projects and have found some issues I'd like to help address.
