### ISSUE TITLE
Problem with overflow on transition

### ISSUE THREAD

**Issue by artsx** [glennflanagan/react-collapsible#8]
Hello, I have a problem,

I have to be able to display menu lists, by default contentOuter is overflow: hidden, I overloaded to tell him that when you open you're overflow: visible, and when you close you're overflow: hidden,

The problem I have is when I decide to reopen the collapse, the text appears as it is in immediatly because it's -> overflow: visible,

There would be a possibility when you want to open it to overflow: auto and when finished it pass in overflow: visible?

Best regards !

**Why i want overflow:visible**
<img width="239" alt="screen shot 2016-09-30 at 12 14 56" src="https://cloud.githubusercontent.com/assets/7711803/18988640/eaa77eaa-8707-11e6-8040-3d8c5a913edb.png">

**Why i need change state for overflow :**
<img width="167" alt="screen shot 2016-09-30 at 12 18 09" src="https://cloud.githubusercontent.com/assets/7711803/18988679/0ce739c4-8708-11e6-9cf5-e6554084a166.png">

**Comment by glennflanagan** [comment]
Hey @artsx,

I'm not sure I'm following what you are trying to attempt here or what the issue is. 

The collapsible is set to `overflow: hidden` in the code to force the content to disappear when it's closed and when the collapsible is open the content is set to `height: auto` so it should be the height it needs to be for the content.

Could you expand a bit more into what your issue is?

Thanks

**Comment by artsx** [comment]
hi @glennflanagan,
Thx for you're reply (sorry for my bad english).

By default, on `.Collapsible__contentOuter` we have `overflow:hidden`
When I try to open my last dropdown, with this` overflow:hidden` we cant see dropdown : 
<img width="238" alt="screen shot 2016-09-30 at 15 05 00" src="https://cloud.githubusercontent.com/assets/7711803/18992603/837b4492-871f-11e6-95d3-7755bb0ef41e.png">

When I fix this `overflow:hidden` by `overflow:visible` I can see my complete dropdown : 
<img width="239" alt="screen shot 2016-09-30 at 15 07 43" src="https://cloud.githubusercontent.com/assets/7711803/18992631/accb7c90-871f-11e6-9d0c-403829ba9278.png">

When I close dropdown, the transition work perfectly.
The problem, it's when I open collapse element, `.Collapsible__contentOuter` is with `overflow:visible` so during the transition, we see all the element is displayed.

My question is : 
When my collapse is closed, I want open -> `overflow:hidden`, when transition it's finished -> `overflow:visible`

I hope I have been clearer,
Thank you for your help!

**Comment by glennflanagan** [comment]
@artsx I've added a new property `overflowWhenOpen` which will allow you to set the CSS overflow value when the Collapsible is open. 

Hope this helps.

**Comment by artsx** [comment]
@glennflanagan it works perfectly, thank you!

**Comment by codydotio** [comment]
@glennflanagan thanks for the `overflowWhenOpen` property, but do you have any idea why it wouldn't work in ie10/11?

**Comment by glennflanagan** [comment]
@codydotio I wouldn't off the top of my head. I've not got a ie10 VM at the moment so I can't test it. I'll give it a check as soon as I can.

**Comment by codydotio** [comment]
@glennflanagan thanks! I can pm my browserstack login if that helps.. it's causing an issue for some of our users

**Comment by glennflanagan** [comment]
That's ok. I can spin up a VM on my Mac as soon as I get chance.
