### ISSUE TITLE
Collapsible not compatible with embedded semantic Grid

### ISSUE THREAD

**Issue by johnreynolds** [glennflanagan/react-collapsible#81]
Before I start whining about my issue, thanks for this component. I appreciate your contribution.

My issue is that I am wrapping a Grid that has Columns, using the Semantic UI React components.
When I wrap the Grid in Collapsible, the widths of the Grid's Columns are no longer honored. Something about Collapsible is overriding the css the Grid needs.

I would appreciate any suggestions on what to I can try. I may have to extract from your example and make my own if I can't figure this out.

Thanks again,
John

**Comment by glennflanagan** [comment]
Hey John. Are you able to create a jsfiddle or codepen with some example code so I can try and debug it?

**Comment by johnreynolds** [comment]
I'm an idiot Glenn.
All I needed to do was set the width of Collapsible explicitly in my css.
Sorry for bothering you.

**Comment by glennflanagan** [comment]
Not a problem. Sometimes asking the question helps you find the answer. We’ve all been there.
