### ISSUE TITLE
className props should apply CSS class in any state

### ISSUE THREAD

**Issue by Sheile** [glennflanagan/react-collapsible#87]
I know, this is the breaking change and can't apply immediately.
When this project will drastic change at v3.0 please consider following proposal.

Currently, this component can receive `className` and `openedClassName`.

- `className`: class name for **CLOSED** component
- `openedClassName`: class name for opened component

Generally `className` prop is known as that to specify class attribute always, like `<div>` element in the react.
https://reactjs.org/docs/dom-elements.html#classname

Current behavior has given some surprising and annoying for me.
IMO, following three props are LGTM.

- `className`: class name without condition
- `closedClassName`: class name for closed component
- `openedClassName`: class name for opened component

**Comment by karltaylor** [comment]
Yeah I completely agree with you - this makes a lot of sense.

**Comment by karltaylor** [comment]
I've made a [release branch](https://github.com/glennflanagan/react-collapsible/tree/release/3.0.0) for this issue you want to make a PR.

**Comment by karltaylor** [comment]
Fixed in `v3.0.0`

**Comment by iMoses-Apiiro** [comment]
@karltaylor what do you mean `v3.0.0` if 11 days ago `v2.10.0` was released? :sweat_smile:

**Comment by karltaylor** [comment]
@iMoses-Apiiro This was originally planned to be in a new major version of `react-collapsible` but it was discarded.

Also you should know that software can still be released at 2.x.x even if 3.x.x exists, otherwise [LTS](https://en.wikipedia.org/wiki/Long-term_support) wouldn't be a thing.

**Comment by iMoses-Apiiro** [comment]
semver is a thing, but you have to admit it's amusing finding a comment from more than 3 years ago talking about a version that was never released :)

are there still plans to release a new major version or was it completely aborted?
the library looks and feels really good but I do believe that some API cleanups could do a lot of good
and i'd be happy to chip in if help is needed

**Comment by karltaylor** [comment]
@iMoses-Apiiro Indeed, a long time ago that!

It's been completely aborted iirc. Personally I would love to take react-collapsible to a whole new level with hooks and css-in-js but don't have the time at the moment. And I'm not sure what direction @glennflanagan wants to do with it, could open up an RFC?

**Comment by glennflanagan** [comment]
@karltaylor I'll be honest I've been too out of the OOS game over the last year or so and I don't have the time to rework it- so I'm not really sure what the future plan should be for this component. 

As for this specific issue it would be a breaking change now to change the behaviour of the `className` prop as users will have already set up their CSS to handle it. If we are to fix it then it would have to be a major version bump (so v3 🙄 ).

As always - PRs are welcome - but we'd need to manage it as a major release.

**Comment by iMoses-Apiiro** [comment]
@glennflanagan I'm more inline with what @karltaylor suggested, which is not dealing only with this specific request but taking the package to the next level. Basically a maintenance refactor to account for all changes in the ecosystem (hooks, modern design patterns, etc). 

Although I'm personally not in favor of adding css-in-js as I think it's too opinionated and what I love about this package is that it's so small and doesn't have dependencies :) 

If working hands are the issue then I can quickly wrap something up for a PR, but is it something you'd be interested in? Keeping the exact same logic but rewriting the entire API for a new major version
