### ISSUE TITLE
Add a test suite

### ISSUE THREAD

**Issue by rsarai** [glennflanagan/react-collapsible#88]

**Comment by karltaylor** [comment]
Do you have a preference @rsarai?

**Comment by rsarai** [comment]
hey @karltaylor, I like Jest:  https://facebook.github.io/jest/.

**Comment by glennflanagan** [comment]
I'd agreed. Jest is by far the simplest to set up

**Comment by karltaylor** [comment]
I wanted to take a look at this since I haven't done much testing before - is it worth using http://airbnb.io/enzyme/ as well?

**Comment by glennflanagan** [comment]
Yes definitely. Jest and Enzyme work brilliantly together.

**Comment by karltaylor** [comment]
Brilliant thanks I'll take a look. Looks great!

**Comment by karltaylor** [comment]
Took a stab at it over here. I can continue to add the default ones and then maybe break out into the more complex things later on. :) 

https://github.com/glennflanagan/react-collapsible/tree/feature/add-test-suite

**Comment by glennflanagan** [comment]
That's perfect to begin with. 👍

**Comment by glennflanagan** [comment]
Now to figure out how to set up Continous Integrations 😄

**Comment by karltaylor** [comment]
Closed #94
