### ISSUE TITLE
Collapsible tag

### ISSUE THREAD

**Issue by illia108** [glennflanagan/react-collapsible#90]
Hi,
thank you for the nice package.

Maybe, I'm missing some config option. But is it possible to change the tag of the Collapsible component (by default it's `<div>`)? 

I'm going to use it inside `tbody`. Thanks

**Comment by karltaylor** [comment]
It's not currently possible, but can be added to 2.1.0, trying to get it out this weekend. 

See this PR https://github.com/glennflanagan/react-collapsible/pull/57 if you want to have a go at adding functionality. Basically does the same thing but for the `span` trigger element.
