### ISSUE TITLE
items stay collapsed with bootstrap 4.1 

### ISSUE THREAD

**Issue by mashehu** [glennflanagan/react-collapsible#91]
Sorry I didn't have time too look deeper into the issue, but this PR https://github.com/twbs/bootstrap/pull/25806 seems to have broken the collapsible elements for me. All of them are hidden because of `.collapse:not(.show) `. Anyway to fix this other then going back to bootstrap 4.0?

**Comment by karltaylor** [comment]
Can you post some code or a codepen?

**Comment by mashehu** [comment]
Okay, looks like the issue came from bootstrap 4.1, sorry for that.
