### ISSUE TITLE
Collapsible doesn't perform on mobile device browsers

### ISSUE THREAD

**Issue by tyhopp** [glennflanagan/react-collapsible#93]
Hi @glennflanagan, thanks for creating this awesome component. Everything works as expected except that on mobile device browsers (Chrome, Safari, etc.), the Collapsible dropdown doesn't appear `onClick`. 

Here's the code I'm using inside a Gatsby project:

```
<Collapsible
					triggerStyle={{
						display: 'flex',
						flexDirection: 'row',
						justifyContent: 'space-between',
						fontFamily: 'karla-bold',
						fontSize: 16,
						color: dark,
						cursor: 'pointer',
						padding: '1em 1.5em',
						borderTop: `solid 1px ${dark8}`,
					}}
					trigger={currentLocale === 'en' ? sectionNameEn : sectionNameDe}
					transitionTime={100}
					easing={'ease-in-out'}
				>
					{data.allContentfulPage.edges.map(page => {
						if (page.node.node_locale === currentLocale) {
							if (page.node.navigationSection === sectionNameEn) {
								return (
									<div>
										<MblNavSection key={page.node.title}>
											<Row>
												<MblNavItem to={page.node.slug} key={page.node.title}>
													{page.node.title}
												</MblNavItem>
											</Row>
										</MblNavSection>
										<div style={{ borderBottom: `solid 1px ${white}` }} />
									</div>
								)
							}
						}
					})}
				</Collapsible>
```

Any help would be greatly appreciated. Thanks!

**Comment by glennflanagan** [comment]
Hey @tyhopp, I can't see anything here that would cause an issue on mobile. Are you able to get an example of it not working into a JSFiddle so we can investigate?

**Comment by tyhopp** [comment]
Hi @glennflanagan thanks for your response! Unfortunately was up against a deadline and didn't have time to properly replicate. Ended up swapping out for another accordion to meet the deadline. 

Still a fan of the project, thanks for maintaining! 🙌
