### ISSUE TITLE
CSS is not applying to the Collaspe

### ISSUE THREAD

**Issue by naren9459** [glennflanagan/react-collapsible#95]
Hi,

I have added the Collasible component. I am getting the Heading and body section but there is not css applied to the component. I just see all text.  up arrow down arrow is also not visible. Animation is working fine.

Is there any css file I need to add?

Please help me what I am doing wrong? Thanks.

**Comment by glennflanagan** [comment]
Hi @naren9459, the component is set up so you can apply your own CSS so it fits into whatever app/website you're putting it in to.

If you need a guide on what the CSS could be you can use the example SASS file https://github.com/glennflanagan/react-collapsible/blob/develop/example/_src/sass/components/_Collapsible.scss

Thanks
