### ISSUE TITLE
collapsible not working in loop

### ISSUE THREAD

**Issue by ramasiva818** [glennflanagan/react-collapsible#96]
I want to display array of values in each individual collapsible

**Comment by glennflanagan** [comment]
@ramasiva818 I'm not sure this is an issue with the Collapsible. You're not adding anything as the children of the Collapsible so only the trigger will render.

I'm going to close this issue for now. If you're able to get a JSFiddle up and running demonstrating the issue then we'll take a look again.

**Comment by ramasiva818** [comment]
`{property.services_mapped.length > 0 ? ( property.services_mapped.map((service_map,i) =>{  <div key={i}> <Collapsible trigger={service_map.request_type} onOpening={()=>{ this.setState({ isOpen : true }) }} onClosing={()=>{ this.setState({ isOpen : false }) }} lazyRender = {true} > </Collapsible> </div> })): null }`

I updated the code like this. But it still not working.

**Comment by glennflanagan** [comment]
@ramasiva818 it's impossible for me to debug from a string of text. Please set up a JSFiddle with an example of your code not working if you want to to help out.

Cheers

**Comment by karltaylor** [comment]
It would also be easier if you use backticks (`) for code formatting - see [#quoting code](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code) here.

**Comment by ramasiva818** [comment]
#@glennflanagan can you please add any example with collapsible within loop.

**Comment by karltaylor** [comment]
@ramasiva818 

```js
['Section 1', 'Section 2', 'Section 3', 'Section 4'].map(section => {
        return (
        <Collapsible trigger={section}>{section}</Collapsible>)
        })
```

https://jsfiddle.net/6jud4trx/

**Comment by ramasiva818** [comment]
`{
    "property_masters": [
        {
            "id": 28,
            "property_name": null,
            "lot": "21",
            "property_desc": "Property Description",
            "property_owner_name": "rams",
            "property_deposited_plan": "hello",
            "property_address": "Hogwarts Floor",
            "latitude": "17.446098",
            "longitude": "78.349851",
            "active": null,
            "created_by_id": 8,
            "updated_by_id": 8,
            "dummy1": null,
            "dummy2": null,
            "dummy3": null,
            "archive": false,
            "deleted_by_id": null,
            "deleted_at": null,
            "created_at": "2018-05-16T13:26:00.000Z",
            "updated_at": "2018-05-16T13:26:01.000Z",
            "user_id": 8,
            "services_mapped": [
                {
                    "id": 110,
                    "upvise_id": "876885",
                    "property_master_id": 28,
                    "assessment_master_id": 1,
                    "request_type": "Documentation for assessment",
                    "request_dt": "2018-05-16T13:27:27.000Z",
                    "status": "requested",
                    "active": true,
                    "close_dt": null,
                    "created_by_id": 8,
                    "updated_by_id": 8,
                    "created_at": "2018-05-16T13:27:27.000Z",
                    "updated_at": "2018-05-16T13:27:29.000Z"
                },
                {
                    "id": 112,
                    "upvise_id": "954663",
                    "property_master_id": 28,
                    "assessment_master_id": 1,
                    "request_type": "Documentation for assessment",
                    "request_dt": "2018-05-21T10:21:24.000Z",
                    "status": "requested",
                    "active": true,
                    "close_dt": null,
                    "created_by_id": 8,
                    "updated_by_id": 8,
                    "created_at": "2018-05-21T10:21:24.000Z",
                    "updated_at": "2018-05-21T10:21:25.000Z"
                },
                {
                    "id": 113,
                    "upvise_id": "694083",
                    "property_master_id": 28,
                    "assessment_master_id": 6,
                    "request_type": "Request Services Mapping",
                    "request_dt": "2018-05-21T10:22:32.000Z",
                    "status": "requested",
                    "active": true,
                    "close_dt": null,
                    "created_by_id": 8,
                    "updated_by_id": 8,
                    "created_at": "2018-05-21T10:22:32.000Z",
                    "updated_at": "2018-05-21T10:22:32.000Z"
                },
                {
                    "id": 114,
                    "upvise_id": "167208",
                    "property_master_id": 28,
                    "assessment_master_id": 7,
                    "request_type": "Request Services Mapping",
                    "request_dt": "2018-05-21T10:22:32.000Z",
                    "status": "requested",
                    "active": true,
                    "close_dt": null,
                    "created_by_id": 8,
                    "updated_by_id": 8,
                    "created_at": "2018-05-21T10:22:32.000Z",
                    "updated_at": "2018-05-21T10:22:33.000Z"
                },
                {
                    "id": 13,
                    "upvise_id": "595725",
                    "property_master_id": 28,
                    "is_one_plmbr_or_drnr": false,
                    "is_sydny_locatd_area": false,
                    "request_dt": "2018-05-21T10:22:22.000Z",
                    "active": null,
                    "status": null,
                    "created_by_id": 8,
                    "updated_by_id": 8,
                    "created_at": "2018-05-21T10:22:22.000Z",
                    "updated_at": "2018-05-21T10:22:22.000Z",
                    "request_type": "DFT Payment"
                }
            ]
        }
    ]
}`

I want show collapsible array of services_mapped objects

**Comment by glennflanagan** [comment]
@ramasiva818 this is not an issue with the Collapsible component. We've given you examples of how to map over an array of data and output a Collapsible for each. The rest is up to you I'm afraid.
