### ISSUE TITLE
Contextual menu in the trigger causes open/close

### ISSUE THREAD

**Issue by robwheatley** [glennflanagan/react-collapsible#98]
Hi there,

Loving this package, works like a dream. However, there's one thing I'm struggling with.

I'm using this package as a 'folder structure' to organise notes in a web app. My notes are the collapsable content and the folder the notes are in is the collapsible trigger, e.g.

**Folder name 1**
-note
-note
**Folder name 2**
-note
-note

So, my trigger is actually a React component that renders the folder name and a little menu icon that appears on hover. Clicking that menu pops up a contextual menu that lets me rename or delete the folder (I'm using react-contexify for that - also a cool package). 

My problem is that clicking on the menu icon not only opens the contextual menu (as it should) but it also triggers the collapse to open/close (which I don't want it to do). I'm guessing that a click on any child element in the trigger causes the trigger, but I would like to stop that 'propagation' - any ideas?

**Comment by karltaylor** [comment]
Is there any way you could set up a JSFiddle for me to have a play around? 😊

**Comment by robwheatley** [comment]
wow - that was a damn quick response. I'll have a go (may take a while, I'm a complete novice hacking with Meteor thinking I rule the world after one Meteor course and zero Javascript or CSS experience). I'll post a link as soon as I get something that 'works' (if I get something that works)!

**Comment by karltaylor** [comment]
@robwheatley not to worry I actually just whipped something up, looks like the trigger definitely fires the collapsible

**Comment by karltaylor** [comment]
So I *can* see a potential fix for this - If you take a look at this [JSFiddle](https://jsfiddle.net/mc1y7tux/). In the `handleTriggerClick` function we pass the `event`, and we can differentiate between the `event.target` (could be span or trigger element). So if it's a button or item with a specific class name etc. We could fire that onClick instead. Gunna have a think how to approach it and how it fits in

**Comment by robwheatley** [comment]
@karltaylor I need to wrap up for the night, but I have a 'hacky' suggestion (after playing with your JSfiddle).

It looks like the button or whatever clickable item you have in the trigger fires with no problems regardless of what handleTriggerClick does. So, how about this as a suggestion:

If someone wants to add an element into the trigger, but not want it to cause a trigger, if they add a class name like 'NoTrigger' to it, your handleTriggerClick function looks for that class name on the event.target and if it sees it, stops. i.e. add the if statement to your  this to your handleTriggerClick function:

```
handleTriggerClick(event) {
    
    event.preventDefault();

    if (this.props.triggerDisabled) {
      return
    }

    if (event.target.className.includes("NoTrigger")) {
     return
    }
.
.
.
```

**Comment by karltaylor** [comment]
I've completely forgot about the Web API [event.stopPropagation](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Examples#Example_5:_Event_Propagation)!

On your `onClick` of your menu item, pass the `event` and call `.stopPropagation()` - this will stop the click event from bubbling to the trigger element.

```js
<button 
  onClick={(event) => {
    console.log('clicked')
    event.stopPropagation()
  }}
>
  test
</button>
```

**Comment by robwheatley** [comment]
@karltaylor Nice one. As it happens, I thought about stopPropagation, but I added to your handleTriggerClick function rather than the button, so it didn't work for me. Doh! of course, it needs to be in the button.

Any, thank you very much - awesome job.
